# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='STag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_id', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TaggedTrucks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.STag')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('stag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.STag')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='taggedtrucks',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Truck'),
        ),
    ]
