# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stag',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='taggedtrucks',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tracking.Truck'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='stag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='tracking.STag'),
        ),
    ]
