# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20170417_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='livetracking',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Mobile'),
        ),
        migrations.AddField(
            model_name='livetracking',
            name='stag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livelocation', to='tracking.STag'),
        ),
    ]
