# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20170424_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetracking',
            name='mobile',
            field=models.CharField(max_length=14),
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
